### ISSUE TITLE
Support for async custom resolver

### ISSUE THREAD

**Issue by aneilbaboo** [userpixel/micromustache#12]
I'd like to be able to use async functions in my custom resolver.  How feasible/easy is it to add an async version of the render function?

E.g.,

```javascript
async customResolver(varName, view) {
  return view[varName] || await lookUpVar(varName);
}
async bar() {
  await micromustache.renderAsync("{{foo}}", {}, customResolver);
}
```

**Comment by userpixel** [comment]
It's a cool feature. Maybe someone can fork the project and make an async version of it. [The main code](https://github.com/userpixel/micromustache/blob/master/lib/render.js) is under 100 SLOC so it shouldn't be hard to modify the render function to return a promise and deal with async `customResolver()` functions.
That being said, I can't see those changes in micromustache due to its performance & size implications. The goal of micromustache is to be super tiny (hence the name) and compatible with MustacheJS.

---

I would fork the repo and make `micromustache-async` (and probably remove the cli tool from `/bin` so it doesn't collide if someone has both sync & async version installed.

**Comment by userpixel** [comment]
Didn't hear anything back. Will close this issue as I don't see it being implemented in this repo :+1:

**Comment by aneilbaboo** [comment]
Makes sense.  Thanks for the response.
